services:
  emotion-api-server:
    build: .
    container_name: emotion-api-server
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - mongo
      - text-emotion
      - video-emotion

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  text-emotion:
    build:
      context: ../text-emotion
    container_name: text-emotion
    ports:
    - "8001:8001"
    restart: unless-stopped
  
  video-emotion:
    build:
      context: ../video-emotion
    container_name: video-emotion
    ports:
      - "8004:8004"
    restart: unless-stopped

volumes:
  mongo_data:
